// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecxtnxftlkwcykydafpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjeHRueGZ0bGt3Y3lreWRhZnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTM1MjksImV4cCI6MjA2NDA2OTUyOX0.QZh34pShku6amm2e93XXvn1pdT6CHBTrbkRTrms2YeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);